name: "github-action-validate-codeowners"
description: "Validate the `CODEOWNERS` metadata file"
inputs:
  token:
    description: "GitHub token (see: https://github.com/mszostok/codeowners-validator/blob/main/docs/gh-token.md)"
    required: false
runs:
  using: "composite"
  steps:
  - name: "Checkout source code at current commit"
    uses: actions/checkout@v4
  - uses: mszostok/codeowners-validator@v0.7.4
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: "Full check of CODEOWNERS"
    with:
      # For now, remove "files" check to allow CODEOWNERS to specify non-existent
      # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
      #   checks: "files,syntax,owners,duppatterns"
      checks: "syntax,owners,duppatterns"
      # GitHub access token is required only if the `owners` check is enabled
      github_access_token: ${{ inputs.token }}
  - uses: mszostok/codeowners-validator@v0.7.4
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: "Syntax check of CODEOWNERS"
    with:
      checks: "syntax,duppatterns"
